name: Rosalind sample data tests

on:
    push:
        branches: ["main"]
        paths:
            - .github/workflows/rosalind-tests.yml
            - "src/main.rs"
            - "src/cli.rs"
            - "src/lib.rs"
            - "src/dna.rs"
            - "Cargo.toml"
            - "Cargo.lock"
    pull_request:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Build
              run: cargo build --verbose
